[features]
seeds = false
skip-lint = false

[programs.localnet]
qst_staking_devnet = "DEVNET_PROGRAM_ID_TO_BE_GENERATED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "DEVNET_PROGRAM_ID_TO_BE_GENERATED"
program = "target/deploy/qst_staking_devnet.so"